// H343 / Spring 2017 Lab 03 Andrew Mathies awmathie

public class Tweet {
    private String content;
    private String author;

    public Tweet(String author, String content) {
	this.author = author;
	this.content = content;
    }

    public void display() {
	System.out.println(author + " tweeted:");
	System.out.println(content);
    }

    public static void main(String[] args) {
	Tweet test1 = new Tweet("Andrew", "I like to program in java, it's one of my favorite programming languages.");
	Tweet test2 = new Tweet("someperson", "It is now possible to learn about a person's mobility preferences from data generated by his or her smartphone");
	Tweet test3 = new Tweet("Olivia", "Man the career fair sucks, I really don't want to go today.");
	test1.display();
	test2.display();
	test3.display();
    }
}
